### ISSUE TITLE
Compatibility and capabilities?

### ISSUE THREAD

**Issue by nlgranger** [sjug/go-zenstates#1]
Hi,
Thank you for this project. There seems to be very relatively little information available on undervolting Ryzen CPUs, especially on linux.
Does this work for undervolting?
What are the supported models (I'm interesting in the Ryzen 7 2700U)?

**Comment by tomasbrod** [comment]
Ryzen 1700 confirmed working. All features except disabling or enabling p-states work.

**Comment by edumarin** [comment]
Hello, 
@nlgranger did you manage to undervolt your Ryzen 7 2700? 
I tried to undervolt mine but I am not sure whether this is actually happening

**Comment by nlgranger** [comment]
@edumarin I postponed my purchase and eventually went for an intel laptop. AFAIK, mobile CPUs are not supported.

**Comment by edumarin** [comment]
@nlgranger thanks for your answer.

@tomasbrod how did you verify that the unverdolting values were being used by your machine? I am pretty sure that my machine is ignoring them as I set them relatively low and the machine still works perfectly

**Comment by tomasbrod** [comment]
@edumarin I read the voltage back with on-board hardware monitoring chip (nuvoton). The voltage is not exact in the last digit. And of course, if set too low, the system crashes under load. Ryzen has some undervoltage protection that kicks in under load and effectively lowers the frequency (skip clocks?). This feature extends the apparent undervolt stability and might be what you are seeing.
Make sure to change the P0 state and test under load.
